# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: David S. Smith, Ph.D.
email: david.smith@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Research Assistant Professor of Radiology and Radiological Sciences
  at Vanderbilt University.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davidssmith.github.io" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  davidssmith

# Build settings
markdown: kramdown
